pipeline {
    agent any           // 아무 에이전트에서 해당 파이프라인 또는 stage를 실행함.

    stages {
        stage('Build Gradle') {
          steps {
            echo 'Build Gradle'
            dir ('./backend/mattro'){
              sh 'chmod +x gradlew'
              sh 'chmod +x dev.sh'
              sh './gradlew clean build'
            }
          }
          post {
            success {
                echo 'Successfully Build Gradle'
            }
            failure {
              error 'This pipeline stops here...'
            }
          }
        }

        stage('Deploy') {
          steps {
            echo 'hello start'
            sshagent (credentials: ['ssh-deploy']) {
              sh """
                ssh -o StrictHostKeyChecking=no ubuntu@3.34.140.235 '
                cd /var/jenkins/workspace/spring/backend/mattro
                ./dev.sh
                '
              """
            }
          }
        }
    }
}